#!/usr/bin/env bash
# Loop over hours from 0 to 12
hour=0
while [ $hour -lt 13 ]
do
    echo "Hour: $hour"
    
    # Loop over minutes from 1 to 59
    minute=1
    while [ $minute -lt 60 ]
    do
        echo $minute
        
        (( minute++ ))
    done
    
    (( hour++ ))
done

